### ISSUE TITLE
GPS Client Standalone App.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#1]
Built a .net windows application that will be stand alone

- This app will need to be running as soon as the tablet starts. **Try to make it a windows service.**
- It will be reading the Modem GPS coordinates (more detail to be provided further down)
- All coordinates will be available on COM6 (this will be a config option, some tablets may have a different COM), on the DOS prompt, you would get it by typing: C:\\> type com6.
- This app will not have a login, and mechanic won't even notice that is running.
- Have a log to keep track of what is going on when capturing data.
- param file will contain: use_id, com_port, server api info, report frequency in minutes... and any other param that you may find useful.

![image](https://cloud.githubusercontent.com/assets/5666297/13012335/ea161554-d178-11e5-9272-19d7e3c27784.png)

**Comment by giovanicani** [comment]
Table view to be used: rep_mechanic_coordinates (rep_mechanic_coordinates_wv)

**Comment by giovanicani** [comment]
Please see file below (starting on second page). For the specs on the GPS output.

[GPSGoogleMapsAPI.pdf](https://github.com/GCSO2/GPS-App/files/128274/GPSGoogleMapsAPI.pdf)

**Comment by giovanicani** [comment]
Tufail, Gene... this is the application I was talking about... we had one for TCS now need to do one for D3S. 

As the 2 quote guys free up, please have them work on this.

Will discuss this further on our next meeting.

**Comment by d3ssupport** [comment]
Done in Development. We need TV for Testing!

**Comment by giovanicani** [comment]
Teamviewer ID: 894744683
Password: z7z26j

**Comment by d3ssupport** [comment]
We are connected with TV but We are not getting Lat and Long through GPS Monitor and DOS Prompt. Can you please confirm .

**Comment by d3sqa** [comment]
@giovanicani, Please see the screenshot below:

The left window is the Console App and the right window is the DOS Prompt. Bottom right side window is the GPS monitor. All the 3 application shows no latitude and longitude data.

![123](https://cloud.githubusercontent.com/assets/13255706/13135411/25ab19b2-d632-11e5-9a0c-2fb412657c9c.png)

**Comment by d3sqa** [comment]
In order to test our application, type 'COM6' and press enter. It is placed on the desktop

**Comment by giovanicani** [comment]
Tablet is indoors. Will ask Gary to put outside. 

--
Giovani Cani

**Comment by d3sqa** [comment]
The application is installed on the tablet as a window service. Coordinates are saved after every 15 minutes.

Following is the file path at which the saving time could be changed from 15 minutes. It is configurable

C:\D3SAPPS\D3S GPS App\D3SGPSApp.exe

![image](https://cloud.githubusercontent.com/assets/13255706/13216775/cec7e444-d97f-11e5-88b8-9e927a92be82.png)

![image](https://cloud.githubusercontent.com/assets/13255706/13216749/a406c572-d97f-11e5-9409-0f9c7078048f.png)

**Comment by giovanicani** [comment]
<add key="LogFolderPath" value="C://D3S//MRO UAT//Logs//" />

Can we please have the logs within the same app directory tree and using relative path instead of fixed path ?

**Comment by giovanicani** [comment]
GPS App getting stuck... see screen shot below... I have changed the capture rate to 5 mins.

Has been almost half an hour last time anything was recorded.

**Need to make sure log has lots of information to be able to better troubleshoot these types of issues**

![image](https://cloud.githubusercontent.com/assets/5666297/13222172/bfcdd3b4-d94c-11e5-872c-74253749417b.png)

**Comment by giovanicani** [comment]
SAME Teamviewer ID - 894 744 683 
Password: development

**Comment by d3sqa** [comment]
The above written point # 01 through 5 are now fixed.

C:\D3S\GPS\Logs\    [Date wise display of logs has been done]

Deployed on the tablet

**Comment by d3sqa** [comment]
Please see config file screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13250089/c90aa2f6-da49-11e5-855a-12c4c1265638.png)

**Comment by giovanicani** [comment]
Thank you! will look into it today.

**Comment by giovanicani** [comment]
3 not done on UAT.

5 not working. I turned off the GPS and still getting coordinates on the UAT and flag GPS_TRACKING_ON_FLAG is still Y, it should be N. **if comX is not providing output the flag should be N and coordinates blank.**

**Comment by d3sqa** [comment]
Point # 03 is done now in UAT.
Context variables are now set

**Comment by giovanicani** [comment]
done. thanks!
